export type SeoPage = {
  pageTitle: string;
  pageSlug: string;
  primaryKeyword: string;
  secondaryKeywords: string;
  targetArea: string;
  pageType: string;
  searchIntent: string;
  volumePerMonth: string;
  keywordDifficulty: string;
  cpc: string;
  priority: string;
  ctaStrategy: string;
};

export const SITE_NAME = "Roof Leak Fixer";
export const DEFAULT_SITE_URL = "https://roofleakfixer.com";
export const PHONE_DISPLAY = "1-888-385-2550";
export const PHONE_E164 = "+18883852550";

export const SEO_PAGES: SeoPage[] = [
  {
    "pageTitle": "Emergency Roof Repair - 24/7 Same-Day Service Canada",
    "pageSlug": "/emergency-roof-repair",
    "primaryKeyword": "emergency roof repair",
    "secondaryKeywords": "emergency roof repair near me, 24 hour roof repair, emergency roofer, emergency roof repair services, same day roof repair",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "900.0",
    "keywordDifficulty": "0.0",
    "cpc": "400.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - sticky phone bar above fold + mid-page callback"
  },
  {
    "pageTitle": "Emergency Roof Leak Repair - Fast Response Canada",
    "pageSlug": "/emergency-roof-leak-repair",
    "primaryKeyword": "emergency roof leak repair",
    "secondaryKeywords": "emergency roof leak, leaking roof emergency, emergency roof leak repair near me, fix roof leak fast, roof leak emergency service",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "170.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - sticky phone bar above fold + urgency CTA"
  },
  {
    "pageTitle": "Emergency Roofer - On-Call 24/7 Canada",
    "pageSlug": "/emergency-roofer",
    "primaryKeyword": "emergency roofer",
    "secondaryKeywords": "emergency roofer near me, emergency roofing contractor, 24 hour roofer, after hours roofer, emergency roofing company",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "400.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - sticky header + click-to-call banner"
  },
  {
    "pageTitle": "Emergency Roof Tarping Service - Storm Response Canada",
    "pageSlug": "/emergency-roof-tarping",
    "primaryKeyword": "emergency roof tarp service",
    "secondaryKeywords": "roof tarping service, roof tarp, emergency roof tarping, tarping a roof, roof tarp near me",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "2.0",
    "cpc": "80.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call CTA with urgency headline"
  },
  {
    "pageTitle": "Roof Leak Repair Canada - Fix Any Leak Fast",
    "pageSlug": "/roof-leak-repair",
    "primaryKeyword": "roof leak repair",
    "secondaryKeywords": "repair roof leak, fix roof leak, leaking roof repair, roof leak repairs, roof leaking repair, how to repair roof leak",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "1100.0",
    "keywordDifficulty": "1.0",
    "cpc": "45.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold + service area selector"
  },
  {
    "pageTitle": "Roof Repair Canada - Professional Roofing Services",
    "pageSlug": "/roof-repair",
    "primaryKeyword": "roof repair",
    "secondaryKeywords": "roof repair services, roof repair company, residential roof repair, roof repair companies, roof repair near me",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "1900.0",
    "keywordDifficulty": "1.0",
    "cpc": "50.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + service area map"
  },
  {
    "pageTitle": "Storm Damage Roof Repair Canada - Insurance Assistance",
    "pageSlug": "/storm-damage-roof-repair",
    "primaryKeyword": "storm damage roof repair",
    "secondaryKeywords": "storm damage roof, roof storm damage, roof damage insurance claim, storm damage roof inspection, wind and hail roof repair",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "50.0",
    "keywordDifficulty": "0.0",
    "cpc": "200.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + insurance claim CTA"
  },
  {
    "pageTitle": "Hail Damage Roof Repair Canada - Free Assessment",
    "pageSlug": "/hail-damage-roof-repair",
    "primaryKeyword": "hail damage roof repair",
    "secondaryKeywords": "hail damage roof, hail damage on roof, roof hail damage, hail damage roof replacement, hail damage roof inspection",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "200.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + free damage assessment CTA"
  },
  {
    "pageTitle": "Wind Damage Roof Repair Canada - 24/7 Response",
    "pageSlug": "/wind-damage-roof-repair",
    "primaryKeyword": "wind damage roof repair",
    "secondaryKeywords": "wind damage to roof, wind damage roof, roof wind damage, wind damaged shingles repair, storm wind roof repair",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "40.0",
    "keywordDifficulty": "1.0",
    "cpc": "170.0",
    "priority": "\ud83d\udfe1 Medium",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Flat Roof Repair Canada - Commercial and Residential",
    "pageSlug": "/flat-roof-repair",
    "primaryKeyword": "flat roof repair",
    "secondaryKeywords": "flat roof repair near me, flat roof leak repair, flat roof leak, commercial flat roof repair, flat roof repair services",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "700.0",
    "keywordDifficulty": "0.0",
    "cpc": "200.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + service types selector"
  },
  {
    "pageTitle": "Ice Dam Removal Canada - Prevent Roof Leaks",
    "pageSlug": "/ice-dam-removal",
    "primaryKeyword": "ice dam removal",
    "secondaryKeywords": "ice dam removal near me, roof ice dam, ice dam on roof, ice dam roof repair, professional ice dam removal",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "80.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + seasonal urgency CTA"
  },
  {
    "pageTitle": "Roof Replacement Canada - Full Roof Replacement Service",
    "pageSlug": "/roof-replacement",
    "primaryKeyword": "roof replacement",
    "secondaryKeywords": "roof replacement near me, residential roof replacement, roof replacement company, roof shingles replacement, asphalt roof replacement",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "1800.0",
    "keywordDifficulty": "0.0",
    "cpc": "35.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + free quote CTA"
  },
  {
    "pageTitle": "Roof Inspection Canada - Free Damage Assessment",
    "pageSlug": "/roof-inspection",
    "primaryKeyword": "roof inspection",
    "secondaryKeywords": "free roof inspection, roof inspection near me, roof inspection services, roof inspection cost, commercial roof inspection",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "700.0",
    "keywordDifficulty": "0.0",
    "cpc": "300.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + book free inspection CTA"
  },
  {
    "pageTitle": "Commercial Roof Repair Canada - All Roof Types",
    "pageSlug": "/commercial-roof-repair",
    "primaryKeyword": "commercial roof repair",
    "secondaryKeywords": "commercial roof inspection, commercial roof replacement, commercial roof leak repair, commercial flat roof repair, commercial roofing company",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "170.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + commercial estimate CTA"
  },
  {
    "pageTitle": "Roof Repair Near Me - Same-Day Service Canada",
    "pageSlug": "/roof-repair-near-me",
    "primaryKeyword": "roof repair near me",
    "secondaryKeywords": "roof repair contractor near me, roof repair companies near me, residential roof repair near me, roof repair services near me",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "800.0",
    "keywordDifficulty": "6.0",
    "cpc": "25.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - postal code selector + click-to-call CTA"
  },
  {
    "pageTitle": "Emergency Roof Repair Near Me - 24/7 Canada",
    "pageSlug": "/emergency-roof-repair-near-me",
    "primaryKeyword": "emergency roof repair near me",
    "secondaryKeywords": "emergency roofer near me, emergency roof leak near me, 24 hour roofer near me, roof leak repair near me, leaking roof repair near me",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "250.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + city lookup widget"
  },
  {
    "pageTitle": "Flat Roof Repair Near Me - Canada",
    "pageSlug": "/flat-roof-repair-near-me",
    "primaryKeyword": "flat roof repair near me",
    "secondaryKeywords": "flat roof leak repair near me, commercial flat roof repair near me, flat roof replacement near me, flat roof contractor near me",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "31.0",
    "cpc": "400.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + service area map"
  },
  {
    "pageTitle": "Roof Replacement Near Me - Canada",
    "pageSlug": "/roof-replacement-near-me",
    "primaryKeyword": "roof replacement near me",
    "secondaryKeywords": "roof replacement contractor near me, residential roof replacement near me, roof replacement companies near me, new roof near me",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "10.0",
    "cpc": "60.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + free estimate CTA"
  },
  {
    "pageTitle": "Roof Leak Repair Near Me - Canada",
    "pageSlug": "/roof-leak-repair-near-me",
    "primaryKeyword": "roof leak repair near me",
    "secondaryKeywords": "leaking roof repair near me, roof leaking repair near me, fix roof leak near me, emergency roof leak near me",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "50.0",
    "keywordDifficulty": "0.0",
    "cpc": "250.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Ice Dam Removal Near Me - Canada",
    "pageSlug": "/ice-dam-removal-near-me",
    "primaryKeyword": "ice dam removal near me",
    "secondaryKeywords": "ice dam removal service near me, professional ice dam removal, ice dam roof repair near me, winter roof repair near me",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "250.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + seasonal urgency CTA"
  },
  {
    "pageTitle": "Roof Inspection Near Me - Free Assessment Canada",
    "pageSlug": "/roof-inspection-near-me",
    "primaryKeyword": "roof inspection near me",
    "secondaryKeywords": "free roof inspection near me, roof damage inspection near me, hail damage inspection near me, roof inspector near me",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "200.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + book inspection CTA"
  },
  {
    "pageTitle": "Average Cost of Roof Replacement in Canada 2025",
    "pageSlug": "/average-cost-of-roof-replacement",
    "primaryKeyword": "average cost of roof replacement",
    "secondaryKeywords": "roof replacement cost, roof replacement cost canada, how much does a new roof cost, cost of new roof, new roof cost canada",
    "targetArea": "Canada (National)",
    "pageType": "Cost Guide",
    "searchIntent": "Informational",
    "volumePerMonth": "800.0",
    "keywordDifficulty": "2.0",
    "cpc": "90.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - inline call CTA + mid-page urgency callout"
  },
  {
    "pageTitle": "Roof Replacement Cost Canada - Full Pricing Guide",
    "pageSlug": "/roof-replacement-cost",
    "primaryKeyword": "roof replacement cost",
    "secondaryKeywords": "roof replacement cost ontario, roof replacement cost calculator canada, asphalt roof replacement cost, average roof replacement cost calgary",
    "targetArea": "Canada (National)",
    "pageType": "Cost Guide",
    "searchIntent": "Informational",
    "volumePerMonth": "500.0",
    "keywordDifficulty": "2.0",
    "cpc": "50.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - inline CTA + cost table + call for quote"
  },
  {
    "pageTitle": "Roof Repair Cost Canada - What to Expect",
    "pageSlug": "/roof-repair-cost",
    "primaryKeyword": "roof repair cost",
    "secondaryKeywords": "how much to repair roof, roof repair cost canada, roof repair price guide, roof repair estimate cost",
    "targetArea": "Canada (National)",
    "pageType": "Cost Guide",
    "searchIntent": "Informational",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "70.0",
    "priority": "\ud83d\udfe1 Medium",
    "ctaStrategy": "Call 1-888-385-2550 - mid-page call CTA + pricing table"
  },
  {
    "pageTitle": "Roof Leak Repair Cost Canada - Pricing Guide",
    "pageSlug": "/roof-leak-repair-cost",
    "primaryKeyword": "roof leak repair cost",
    "secondaryKeywords": "how much to repair roof leak, roof leak repair price, roof leak fix cost, leaking roof repair cost",
    "targetArea": "Canada (National)",
    "pageType": "Cost Guide",
    "searchIntent": "Informational",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "190.0",
    "priority": "\ud83d\udfe1 Medium",
    "ctaStrategy": "Call 1-888-385-2550 - inline call CTA + cost breakdown"
  },
  {
    "pageTitle": "Roof Leaking - What to Do Right Now Canada",
    "pageSlug": "/roof-leaking-what-to-do",
    "primaryKeyword": "roof leaking",
    "secondaryKeywords": "leaking roof, my roof is leaking, roof leak, what to do when roof is leaking, roof leaking inside",
    "targetArea": "Canada (National)",
    "pageType": "Symptom Page",
    "searchIntent": "Informational",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "0.0",
    "cpc": "170.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - urgency callout + mid-page emergency CTA"
  },
  {
    "pageTitle": "Roof Leak Detection Canada - Find the Source Fast",
    "pageSlug": "/roof-leak-detection",
    "primaryKeyword": "roof leak detection",
    "secondaryKeywords": "find roof leak, infrared roof leak detection, roof leak inspection, roof leak source, roof water leak detection",
    "targetArea": "Canada (National)",
    "pageType": "Symptom Page",
    "searchIntent": "Informational",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "180.0",
    "priority": "\ud83d\udfe1 Medium",
    "ctaStrategy": "Call 1-888-385-2550 - mid-page emergency phone CTA"
  },
  {
    "pageTitle": "Ice Dam on Roof Canada - Signs, Risks and Removal",
    "pageSlug": "/ice-dam-on-roof",
    "primaryKeyword": "ice dam on roof",
    "secondaryKeywords": "ice dam roof, roof ice dam, what is an ice dam on a roof, ice dam damage, ice dam removal cost",
    "targetArea": "Canada (National)",
    "pageType": "Symptom Page",
    "searchIntent": "Informational",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "6.0",
    "cpc": "50.0",
    "priority": "\ud83d\udfe1 Medium",
    "ctaStrategy": "Call 1-888-385-2550 - seasonal urgency callout + mid-page call CTA"
  },
  {
    "pageTitle": "Hail Damage Roof Canada - Assessment and Repair Guide",
    "pageSlug": "/hail-damage-roof",
    "primaryKeyword": "hail damage roof",
    "secondaryKeywords": "signs of hail damage on roof, hail damage to roof shingles, roof hail damage inspection, hail roof damage assessment",
    "targetArea": "Canada (National)",
    "pageType": "Symptom Page",
    "searchIntent": "Informational",
    "volumePerMonth": "80.0",
    "keywordDifficulty": "3.0",
    "cpc": "200.0",
    "priority": "\ud83d\udfe1 Medium",
    "ctaStrategy": "Call 1-888-385-2550 - mid-page CTA + free inspection offer"
  },
  {
    "pageTitle": "Roof Insurance Claim Canada - Storm and Leak Coverage Guide",
    "pageSlug": "/roof-insurance-claim",
    "primaryKeyword": "roof insurance claim",
    "secondaryKeywords": "roof damage insurance claim, roof leak insurance claim, storm damage roof insurance claim, home insurance claim for roof repair, hail damage roof insurance",
    "targetArea": "Canada (National)",
    "pageType": "Symptom Page",
    "searchIntent": "Informational",
    "volumePerMonth": "60.0",
    "keywordDifficulty": "1.0",
    "cpc": "190.0",
    "priority": "\ud83d\udfe1 Medium",
    "ctaStrategy": "Call 1-888-385-2550 - inline call CTA + claim assistance offer"
  },
  {
    "pageTitle": "Roof Repair Toronto ON - Same-Day Emergency Service",
    "pageSlug": "/roof-repair-toronto",
    "primaryKeyword": "roof repair toronto",
    "secondaryKeywords": "roof repair north york, toronto roof repair, emergency roof repair toronto, roof leak repair toronto, residential roof repair toronto",
    "targetArea": "Toronto, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "1200.0",
    "keywordDifficulty": "48.0",
    "cpc": "450.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - local header bar + click-to-call"
  },
  {
    "pageTitle": "Emergency Roof Repair Toronto ON - 24/7 Response",
    "pageSlug": "/emergency-roof-repair-toronto",
    "primaryKeyword": "emergency roof repair toronto",
    "secondaryKeywords": "emergency roofer toronto, roof leak emergency toronto, 24 hour roofer toronto, emergency roof leak repair toronto",
    "targetArea": "Toronto, ON",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "400.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - sticky phone bar + emergency urgency CTA"
  },
  {
    "pageTitle": "Flat Roof Repair Toronto ON - Commercial and Residential",
    "pageSlug": "/flat-roof-repair-toronto",
    "primaryKeyword": "flat roof repair toronto",
    "secondaryKeywords": "flat roof replacement toronto, flat roof leak toronto, flat roof contractor toronto, toronto flat roof repair, commercial flat roof toronto",
    "targetArea": "Toronto, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "12.0",
    "cpc": "600.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + flat roof service types"
  },
  {
    "pageTitle": "Roof Leak Repair Toronto ON - Fix Any Leak Fast",
    "pageSlug": "/roof-leak-repair-toronto",
    "primaryKeyword": "roof leak repair toronto",
    "secondaryKeywords": "roof leaking toronto, fix roof leak toronto, toronto roof leak, emergency roof leak toronto, roof water leak toronto",
    "targetArea": "Toronto, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "400.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold + urgency CTA"
  },
  {
    "pageTitle": "Flat Roof Replacement Toronto ON - Full Service",
    "pageSlug": "/flat-roof-replacement-toronto",
    "primaryKeyword": "flat roof replacement toronto",
    "secondaryKeywords": "flat roof replacement cost toronto, torch on roof replacement toronto, flat roof toronto, flat roof replacement near me toronto",
    "targetArea": "Toronto, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "17.0",
    "cpc": "1600.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + free estimate button"
  },
  {
    "pageTitle": "Roof Repair North York ON - Serving All Neighborhoods",
    "pageSlug": "/roof-repair-north-york",
    "primaryKeyword": "roof repair north york",
    "secondaryKeywords": "roof leak repair north york, emergency roof repair north york, roofing contractor north york, flat roof repair north york",
    "targetArea": "North York, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "1.0",
    "cpc": "400.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Mississauga ON - Fast and Reliable",
    "pageSlug": "/roof-repair-mississauga",
    "primaryKeyword": "roof repair mississauga",
    "secondaryKeywords": "flat roof repair mississauga, roof leak repair mississauga, emergency roof repair mississauga, roofing contractor mississauga",
    "targetArea": "Mississauga, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "18.0",
    "cpc": "350.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - local click-to-call + service area map"
  },
  {
    "pageTitle": "Roof Repair Brampton ON - Emergency and Scheduled Service",
    "pageSlug": "/roof-repair-brampton",
    "primaryKeyword": "roof repair brampton",
    "secondaryKeywords": "emergency roof repair brampton, roof leak brampton, roofing contractor brampton, flat roof repair brampton",
    "targetArea": "Brampton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "500.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Markham ON - Expert Roofing Team",
    "pageSlug": "/roof-repair-markham",
    "primaryKeyword": "roof repair markham",
    "secondaryKeywords": "roof leak repair markham, flat roof repair markham, emergency roof repair markham, roofing contractor markham",
    "targetArea": "Markham, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "2.0",
    "cpc": "450.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Vaughan ON - All Roof Types Covered",
    "pageSlug": "/roof-repair-vaughan",
    "primaryKeyword": "roof repair vaughan",
    "secondaryKeywords": "vaughan roof repair, flat roof repair vaughan, emergency roof repair vaughan, roof leak repair vaughan, roof replacement vaughan",
    "targetArea": "Vaughan, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "4.0",
    "cpc": "350.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Richmond Hill ON - Local Roofing Experts",
    "pageSlug": "/roof-repair-richmond-hill",
    "primaryKeyword": "roof repair richmond hill",
    "secondaryKeywords": "richmond hill roof repair, flat roof repair richmond hill, emergency roof repair richmond hill, roof leak repair richmond hill",
    "targetArea": "Richmond Hill, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "350.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Newmarket ON - Fast Storm and Leak Response",
    "pageSlug": "/roof-repair-newmarket",
    "primaryKeyword": "roof repair newmarket",
    "secondaryKeywords": "newmarket roof repair, emergency roof repair newmarket, roof leak repair newmarket, roofing contractor newmarket",
    "targetArea": "Newmarket, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "60.0",
    "keywordDifficulty": "12.0",
    "cpc": "900.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Aurora ON - Reliable Residential Roofing",
    "pageSlug": "/roof-repair-aurora",
    "primaryKeyword": "roof repair aurora",
    "secondaryKeywords": "aurora roof repair, roof leak repair aurora, emergency roof repair aurora, roofing contractor aurora, flat roof repair aurora",
    "targetArea": "Aurora, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "350.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Pickering ON - Same-Day Leak and Storm Service",
    "pageSlug": "/roof-repair-pickering",
    "primaryKeyword": "roof repair pickering",
    "secondaryKeywords": "pickering roof repair, roof leak repair pickering, emergency roof repair pickering, roofing contractor pickering",
    "targetArea": "Pickering, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "600.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Oshawa ON - Emergency and Scheduled Service",
    "pageSlug": "/roof-repair-oshawa",
    "primaryKeyword": "roof repair oshawa",
    "secondaryKeywords": "oshawa roof repair, roof leak repair oshawa, emergency roof repair oshawa, flat roof repair oshawa, roofing contractor oshawa",
    "targetArea": "Oshawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "12.0",
    "cpc": "400.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Ajax ON - Local Storm and Leak Experts",
    "pageSlug": "/roof-repair-ajax",
    "primaryKeyword": "roof repair ajax",
    "secondaryKeywords": "ajax roof repair, roof leak repair ajax, emergency roof repair ajax, flat roof repair ajax, roofing contractor ajax",
    "targetArea": "Ajax, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "60.0",
    "keywordDifficulty": "2.0",
    "cpc": "300.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Whitby ON - Fast Storm Response",
    "pageSlug": "/roof-repair-whitby",
    "primaryKeyword": "roof repair whitby",
    "secondaryKeywords": "roof leak repair whitby, emergency roof repair whitby, roofing contractor whitby, flat roof repair whitby",
    "targetArea": "Whitby, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "17.0",
    "cpc": "600.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Hamilton ON - All Roof Types",
    "pageSlug": "/roof-repair-hamilton",
    "primaryKeyword": "roof repair hamilton",
    "secondaryKeywords": "hamilton roof repair, roof leak repair hamilton, roof replacement hamilton, emergency roof repair hamilton",
    "targetArea": "Hamilton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "7.0",
    "cpc": "900.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + service area coverage"
  },
  {
    "pageTitle": "Roof Replacement Hamilton ON - Reliable Roofing",
    "pageSlug": "/roof-replacement-hamilton",
    "primaryKeyword": "roof replacement hamilton",
    "secondaryKeywords": "new roof hamilton, roof replacement cost hamilton, hamilton roof replacement, full roof replacement hamilton",
    "targetArea": "Hamilton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "1000.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + free estimate button"
  },
  {
    "pageTitle": "Roof Repair Burlington ON - Residential and Commercial",
    "pageSlug": "/roof-repair-burlington",
    "primaryKeyword": "roof repair burlington",
    "secondaryKeywords": "burlington roof repair, flat roof repair burlington, emergency roof repair burlington, roof leak repair burlington, roof replacement burlington",
    "targetArea": "Burlington, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "15.0",
    "cpc": "800.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Oakville ON - Residential Specialists",
    "pageSlug": "/roof-repair-oakville",
    "primaryKeyword": "roof repair oakville",
    "secondaryKeywords": "flat roof repair oakville, roof replacement oakville, flat roof repair burlington, roof leak oakville, emergency roof repair oakville",
    "targetArea": "Oakville, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "18.0",
    "cpc": "500.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + local trust signals"
  },
  {
    "pageTitle": "Roof Repair Barrie ON - Emergency Roofing Service",
    "pageSlug": "/roof-repair-barrie",
    "primaryKeyword": "barrie roof repair",
    "secondaryKeywords": "roof repair barrie, roof replacement barrie, emergency roof repair barrie, flat roof repair barrie, roof leak barrie",
    "targetArea": "Barrie, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "1000.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + urgency header"
  },
  {
    "pageTitle": "Roof Repair Guelph ON - Storm Damage and Leak Experts",
    "pageSlug": "/roof-repair-guelph",
    "primaryKeyword": "roof repair guelph",
    "secondaryKeywords": "guelph roof repair, roof leak repair guelph, emergency roof repair guelph, flat roof repair guelph, roofing contractor guelph",
    "targetArea": "Guelph, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "90.0",
    "keywordDifficulty": "0.0",
    "cpc": "600.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Kitchener ON - All Roof Types",
    "pageSlug": "/roof-repair-kitchener",
    "primaryKeyword": "roof repair kitchener",
    "secondaryKeywords": "kitchener roof repair, roof repair kitchener waterloo, roof leak repair kitchener, emergency roof repair kitchener, flat roof repair kitchener",
    "targetArea": "Kitchener, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "80.0",
    "keywordDifficulty": "2.0",
    "cpc": "200.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair London ON - Storm Damage and Leak Specialists",
    "pageSlug": "/roof-repair-london-ontario",
    "primaryKeyword": "roof repair london ontario",
    "secondaryKeywords": "london ontario roof repair, roof leak repair london ontario, emergency roof repair london ontario, roofing contractor london ontario",
    "targetArea": "London, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "23.0",
    "cpc": "500.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Leak Repair Ottawa ON - 24/7 Emergency Service",
    "pageSlug": "/roof-leak-repair-ottawa",
    "primaryKeyword": "roof leak repair ottawa",
    "secondaryKeywords": "roof repair ottawa, emergency roof repair ottawa, roof replacement ottawa, flat roof repair ottawa",
    "targetArea": "Ottawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "1000.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + emergency service badge"
  },
  {
    "pageTitle": "Roof Replacement Ottawa ON - Full Service Roofing",
    "pageSlug": "/roof-replacement-ottawa",
    "primaryKeyword": "roof replacement ottawa",
    "secondaryKeywords": "new roof ottawa, roof replacement cost ottawa, roof replacement contractors ottawa, ottawa roof replacement",
    "targetArea": "Ottawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "1300.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + free estimate CTA"
  },
  {
    "pageTitle": "Roof Repair St. Catharines ON - Fast and Affordable",
    "pageSlug": "/roof-repair-st-catharines",
    "primaryKeyword": "roof repair st. catharines",
    "secondaryKeywords": "roof replacement st. catharines, roof leak st. catharines, roofing contractor st. catharines, emergency roof repair st. catharines",
    "targetArea": "St. Catharines, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "300.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Calgary AB - Storm and Leak Specialists",
    "pageSlug": "/roof-repair-calgary",
    "primaryKeyword": "roof repair calgary",
    "secondaryKeywords": "calgary roof repair, emergency roof repair calgary, hail damage roof repair calgary, roof leak repair calgary, flat roof repair calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "600.0",
    "keywordDifficulty": "45.0",
    "cpc": "1000.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - sticky phone bar + hail damage hook"
  },
  {
    "pageTitle": "Emergency Roof Repair Calgary AB - 24/7 Fast Response",
    "pageSlug": "/emergency-roof-repair-calgary",
    "primaryKeyword": "emergency roof repair calgary",
    "secondaryKeywords": "emergency roofer calgary, 24 hour roofer calgary, roof leak emergency calgary, emergency roof leak repair calgary",
    "targetArea": "Calgary, AB",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "1900.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - sticky phone bar + full-width emergency CTA"
  },
  {
    "pageTitle": "Roof Leak Repair Calgary AB - Fix Any Leak Same Day",
    "pageSlug": "/roof-leak-repair-calgary",
    "primaryKeyword": "roof leak repair calgary",
    "secondaryKeywords": "calgary roof leak repair, leaking roof calgary, roof leak calgary, fix roof leak calgary, roof water leak calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "6.0",
    "cpc": "1000.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold + urgency CTA"
  },
  {
    "pageTitle": "Hail Damage Roof Repair Calgary AB - Insurance Help",
    "pageSlug": "/hail-damage-roof-repair-calgary",
    "primaryKeyword": "hail damage roof repair calgary",
    "secondaryKeywords": "hail damage roof calgary, roof damage insurance claim calgary, hail roof damage calgary, roof replacement insurance claim calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "800.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + insurance claim assist CTA"
  },
  {
    "pageTitle": "Flat Roof Repair Calgary AB - Commercial and Residential",
    "pageSlug": "/flat-roof-repair-calgary",
    "primaryKeyword": "flat roof repair calgary",
    "secondaryKeywords": "flat roof replacement calgary, flat roof contractor calgary, commercial flat roof repair calgary, flat roof leak calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "30.0",
    "cpc": "900.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + flat roof types CTA"
  },
  {
    "pageTitle": "Roof Replacement Calgary AB - Full Service Roofing",
    "pageSlug": "/roof-replacement-calgary",
    "primaryKeyword": "roof replacement calgary",
    "secondaryKeywords": "roof replacement cost calgary, average roof replacement cost calgary, new roof calgary, roof replacement contractors calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "34.0",
    "cpc": "700.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + free estimate button"
  },
  {
    "pageTitle": "Roof Inspection Calgary AB - Free Hail and Storm Check",
    "pageSlug": "/roof-inspection-calgary",
    "primaryKeyword": "roof inspection calgary",
    "secondaryKeywords": "free roof inspection calgary, hail damage inspection calgary, roof damage assessment calgary, roof inspector calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "400.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + book free inspection"
  },
  {
    "pageTitle": "Roof Repair Edmonton AB - Storm and Leak Experts",
    "pageSlug": "/roof-repair-edmonton",
    "primaryKeyword": "roof repair edmonton",
    "secondaryKeywords": "emergency roof repair edmonton, roof leak repair edmonton, flat roof repair edmonton, roofing contractor edmonton",
    "targetArea": "Edmonton, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "12.0",
    "cpc": "800.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold + service area map"
  },
  {
    "pageTitle": "Roof Replacement Edmonton AB - Full Roof Service",
    "pageSlug": "/roof-replacement-edmonton",
    "primaryKeyword": "roof replacement edmonton",
    "secondaryKeywords": "edmonton roof replacement, new roof edmonton, roof replacement cost edmonton, roof replacement contractors edmonton",
    "targetArea": "Edmonton, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "17.0",
    "cpc": "600.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + free quote CTA"
  },
  {
    "pageTitle": "Roof Inspection Edmonton AB - Free Damage Assessment",
    "pageSlug": "/roof-inspection-edmonton",
    "primaryKeyword": "roof inspection edmonton",
    "secondaryKeywords": "free roof inspection edmonton, roof damage inspection edmonton, hail damage inspection edmonton, roof inspector edmonton",
    "targetArea": "Edmonton, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "300.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + book free inspection"
  },
  {
    "pageTitle": "Roof Repair Red Deer AB - Residential and Storm Damage",
    "pageSlug": "/roof-repair-red-deer",
    "primaryKeyword": "roof repair red deer",
    "secondaryKeywords": "red deer roof repair, roof leak repair red deer, emergency roof repair red deer, flat roof repair red deer, hail damage roof repair red deer",
    "targetArea": "Red Deer, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "80.0",
    "keywordDifficulty": "21.0",
    "cpc": "300.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Airdrie AB - Hail and Storm Specialists",
    "pageSlug": "/roof-repair-airdrie",
    "primaryKeyword": "roof repair airdrie",
    "secondaryKeywords": "airdrie roof repair, roof leak repair airdrie, emergency roof repair airdrie, hail damage roof repair airdrie, roofing contractor airdrie",
    "targetArea": "Airdrie, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "10.0",
    "keywordDifficulty": "0.0",
    "cpc": "800.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Lethbridge AB - Leak and Storm Response",
    "pageSlug": "/roof-repair-lethbridge",
    "primaryKeyword": "roof repair lethbridge",
    "secondaryKeywords": "lethbridge roof repair, flat roof repair lethbridge, roof leak repair lethbridge, emergency roof repair lethbridge, hail damage roof lethbridge",
    "targetArea": "Lethbridge, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "10.0",
    "keywordDifficulty": "0.0",
    "cpc": "300.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Vancouver BC - Leak and Storm Experts",
    "pageSlug": "/roof-repair-vancouver",
    "primaryKeyword": "roof repair vancouver",
    "secondaryKeywords": "roof leak repair vancouver, flat roof repair vancouver, roof replacement vancouver, emergency roof repair vancouver",
    "targetArea": "Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "800.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + service area map"
  },
  {
    "pageTitle": "Flat Roof Replacement Vancouver BC - Full Service",
    "pageSlug": "/flat-roof-replacement-vancouver",
    "primaryKeyword": "flat roof replacement vancouver",
    "secondaryKeywords": "flat roof repair vancouver, flat roof contractor vancouver, commercial flat roof vancouver, torch on roof replacement vancouver",
    "targetArea": "Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "1200.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + flat roof estimate CTA"
  },
  {
    "pageTitle": "Roof Replacement Vancouver BC - Full Roofing Service",
    "pageSlug": "/roof-replacement-vancouver",
    "primaryKeyword": "roof replacement vancouver",
    "secondaryKeywords": "new roof vancouver, roof replacement cost vancouver, roof replacement contractors vancouver, shingle replacement vancouver",
    "targetArea": "Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "33.0",
    "cpc": "800.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + free estimate button"
  },
  {
    "pageTitle": "Roof Repair Coquitlam BC - Same-Day Service",
    "pageSlug": "/roof-repair-coquitlam",
    "primaryKeyword": "roof repair coquitlam",
    "secondaryKeywords": "coquitlam roof repair, roof leak coquitlam, emergency roof repair coquitlam, flat roof repair coquitlam",
    "targetArea": "Coquitlam, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "1200.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Burnaby BC - Residential and Commercial",
    "pageSlug": "/roof-repair-burnaby",
    "primaryKeyword": "roof shingle repair burnaby",
    "secondaryKeywords": "roof repair burnaby, roof leak burnaby, emergency roof repair burnaby, flat roof repair burnaby, roof replacement burnaby",
    "targetArea": "Burnaby, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "0.0",
    "cpc": "800.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call + service area coverage"
  },
  {
    "pageTitle": "Roof Repair Surrey BC - Storm Damage and Leak Response",
    "pageSlug": "/roof-repair-surrey",
    "primaryKeyword": "roof repair surrey",
    "secondaryKeywords": "surrey roof repair, roof leak repair surrey, emergency roof repair surrey, flat roof repair surrey, roofing contractor surrey",
    "targetArea": "Surrey, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "27.0",
    "cpc": "900.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Langley BC - All Roof Types Covered",
    "pageSlug": "/roof-repair-langley",
    "primaryKeyword": "roof repair langley",
    "secondaryKeywords": "langley roof repair, roof leak repair langley, emergency roof repair langley, flat roof repair langley, roofing contractor langley",
    "targetArea": "Langley, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "80.0",
    "keywordDifficulty": "9.0",
    "cpc": "900.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Abbotsford BC - Storm Damage Specialists",
    "pageSlug": "/roof-repair-abbotsford",
    "primaryKeyword": "roof repair abbotsford",
    "secondaryKeywords": "abbotsford roof repair, roof leak repair abbotsford, emergency roof repair abbotsford, flat roof repair abbotsford",
    "targetArea": "Abbotsford, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "24.0",
    "cpc": "1000.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Kelowna BC - Leak, Storm and Hail Damage",
    "pageSlug": "/roof-repair-kelowna",
    "primaryKeyword": "roof repair kelowna",
    "secondaryKeywords": "kelowna roof repair, roof leak repair kelowna, emergency roof repair kelowna, flat roof repair kelowna, storm damage roof repair kelowna",
    "targetArea": "Kelowna, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "600.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Victoria BC - Residential and Commercial",
    "pageSlug": "/roof-repair-victoria",
    "primaryKeyword": "roof repair victoria",
    "secondaryKeywords": "victoria roof repair, roof leak repair victoria, emergency roof repair victoria, flat roof repair victoria, roofing contractor victoria bc",
    "targetArea": "Victoria, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "30.0",
    "keywordDifficulty": "9.0",
    "cpc": "500.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Saskatoon SK - All Roof Types and Services",
    "pageSlug": "/roof-repair-saskatoon",
    "primaryKeyword": "roof repair saskatoon",
    "secondaryKeywords": "saskatoon roof repair, roof leak repair saskatoon, emergency roof repair saskatoon, flat roof repair saskatoon, roofing contractor saskatoon",
    "targetArea": "Saskatoon, SK",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "0.0",
    "cpc": "170.0",
    "priority": "\ud83d\udfe1 Medium",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Regina SK - Leak and Storm Specialists",
    "pageSlug": "/roof-repair-regina",
    "primaryKeyword": "roof repair regina",
    "secondaryKeywords": "regina roof repair, roof leak repair regina, emergency roof repair regina, flat roof repair regina, roofing contractor regina",
    "targetArea": "Regina, SK",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "50.0",
    "keywordDifficulty": "0.0",
    "cpc": "190.0",
    "priority": "\ud83d\udfe1 Medium",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Winnipeg MB - All Roof Types and Services",
    "pageSlug": "/roof-repair-winnipeg",
    "primaryKeyword": "roof repair winnipeg",
    "secondaryKeywords": "roof leak repair winnipeg, emergency roof repair winnipeg, flat roof repair winnipeg, roof replacement winnipeg, roofing contractor winnipeg",
    "targetArea": "Winnipeg, MB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "38.0",
    "cpc": "200.0",
    "priority": "\ud83d\udfe0 High",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  },
  {
    "pageTitle": "Roof Repair Halifax NS - Storm Damage and Leak Experts",
    "pageSlug": "/roof-repair-halifax",
    "primaryKeyword": "roof repair halifax",
    "secondaryKeywords": "halifax roof repair, roof leak repair halifax, emergency roof repair halifax, flat roof repair halifax, roofing contractor halifax",
    "targetArea": "Halifax, NS",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "80.0",
    "keywordDifficulty": "0.0",
    "cpc": "300.0",
    "priority": "\ud83d\udd34 Top Priority",
    "ctaStrategy": "Call 1-888-385-2550 - click-to-call above fold"
  }
] as SeoPage[];

export const CITY_PAGES = SEO_PAGES.filter((page) =>
  page.pageType.toLowerCase().includes("city") ||
  (/^[^,]+,\s*[A-Z]{2}$/.test(page.targetArea))
);
export const SERVICE_HUBS = SEO_PAGES.filter((page) =>
  !page.pageSlug.startsWith("/blog/") &&
  !page.pageType.toLowerCase().includes("symptom") &&
  !page.pageType.toLowerCase().includes("guide") &&
  !CITY_PAGES.some((cityPage) => cityPage.pageSlug === page.pageSlug)
);
export const BLOG_POSTS = SEO_PAGES.filter((page) =>
  page.pageSlug.startsWith("/blog/") ||
  page.pageType.toLowerCase().includes("blog") ||
  page.pageType.toLowerCase().includes("symptom") ||
  page.pageType.toLowerCase().includes("guide")
);

export function toPath(slug: string) {
  return slug.startsWith("/") ? slug : `/${slug}`;
}

export function stripPath(pathname: string) {
  return pathname.replace(/^\/+/, "").replace(/\/+$/, "");
}

export function getSiteUrl() {
  return process.env.NEXT_PUBLIC_SITE_URL || DEFAULT_SITE_URL;
}

export function absoluteUrl(path: string) {
  return `${getSiteUrl()}${path}`;
}

export function bySlug(slugSegment: string) {
  return SEO_PAGES.find((page) => stripPath(page.pageSlug) === stripPath(slugSegment)) ?? null;
}

export function cityFromTargetArea(targetArea: string) {
  return targetArea.split(",")[0]?.trim() || targetArea;
}

export function serviceTopic(page: SeoPage) {
  const lowered = page.pageTitle.toLowerCase();
  if (lowered.includes("storm")) return "Storm Damage Roof Repair";
  if (lowered.includes("flat roof")) return "Flat Roof Leak Repair";
  if (lowered.includes("ice dam")) return "Ice Dam Roof Leak Repair";
  if (lowered.includes("inspection")) return "Emergency Roof Inspection";
  return "Emergency Roof Leak Repair";
}

export function relatedPages(page: SeoPage, limit = 12) {
  const topic = serviceTopic(page);
  return CITY_PAGES.filter((item) => item.pageSlug !== page.pageSlug && serviceTopic(item) === topic).slice(0, limit);
}
